---
services:
  minio:
    image: minio/minio:${MINIO_TAG} # Use the recommended image from quay.io
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio # Replace with your desired access key
      MINIO_ROOT_PASSWORD: minioadmin # Replace with your desired secret key
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console UI port
    command: ["server", "--console-address", ":9001", "/data"] # Command to start the MinIO server and console
    volumes:
      - ${MINIO_DATA}:/data # Mount a named volume for persistent storage
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
